require 'rubygems'
Gem::manage_gems
require 'rake/gempackagetask'

spec = Gem::Specification.new do |s|
  s.name = "openly_sociable_micro"
  s.version = "0.0.1"
  s.author = "Pradeep Elankumaran"
  s.email = "pradeep@intridea.com"
  s.homepage = "http://www.intridea.com"
  s.summary = "OpenlySociable Micro is an drop-in OpenSocial microframework that makes it easy "+
              "to write and host widgets for OpenSocial containers"
  s.platform = Gem::Platform::RUBY
  s.files = FileList["Rakefile", "README", "{bin,lib,examples,test}/**/*"].to_a
  s.require_path = "lib"
  s.add_dependency("camping", ">= 1.5.180")
  s.add_dependency("builder", ">= 2.1.2")
  s.add_dependency("mongrel", ">= 1.1")
end

Rake::GemPackageTask.new(spec) do |pkg|
  pkg.need_tar = true
end

task :default => "pkg/#{spec.name}-#{spec.version}.gem" do
  puts "generated latest version"
end